ALTER TABLE "MembershipCard" DROP CONSTRAINT IF EXISTS "MembershipCard_userId_fkey";

ALTER TABLE "MembershipCard"
ADD COLUMN "firstName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "lastName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "school" TEXT NOT NULL DEFAULT '',
ADD COLUMN "level" TEXT NOT NULL DEFAULT '',
ADD COLUMN "city" TEXT NOT NULL DEFAULT '',
ADD COLUMN "photoDataUrl" TEXT,
ALTER COLUMN "userId" DROP NOT NULL,
ALTER COLUMN "expiresAt" DROP NOT NULL,
ALTER COLUMN "qrCode" TYPE TEXT;

ALTER TABLE "MembershipCard"
ALTER COLUMN "firstName" DROP DEFAULT,
ALTER COLUMN "lastName" DROP DEFAULT,
ALTER COLUMN "email" DROP DEFAULT,
ALTER COLUMN "phone" DROP DEFAULT,
ALTER COLUMN "school" DROP DEFAULT,
ALTER COLUMN "level" DROP DEFAULT,
ALTER COLUMN "city" DROP DEFAULT;

CREATE INDEX "MembershipCard_email_idx" ON "MembershipCard"("email");
CREATE INDEX "MembershipCard_createdAt_idx" ON "MembershipCard"("createdAt");

ALTER TABLE "MembershipCard" ADD CONSTRAINT "MembershipCard_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
